### ISSUE TITLE
CMake failed to build fftw on Mac os 10.14 

### ISSUE THREAD

**Issue by hsheng94** [EMsoft-org/EMsoftSuperbuild#12]
Hello: 

I am trying to build on a mac. But it always gives the error message that project fftw fails. 

Haos-MacBook-Pro:Debug hao_sheng$ cmake -DEMsoft_SDK=/Users/hao_sheng/EMsoft/EMsoft_SDK -DCMAKE_BUILD_TYPE=Debug ../
-- EMsoft_SDK Folder: /Users/hao_sheng/EMsoft/EMsoft_SDK
-- EMsoft_SDK_FILE:   /Users/hao_sheng/EMsoft/EMsoft_SDK/EMsoft_SDK.cmake
-- Workspace Folder:   
-- Found macOS 10.14 Mojave as the host. Darwin Version:18
-- External Project: fftw
-- External Project: jsonfortran
-- External Project: bcls
-- External Project: CLFortran
-- External Project: Eigen
-- External Project: hdf5
-- External Project: tbb: 2019_20181203
-- EMsoft_SDK: /Users/hao_sheng/EMsoft/EMsoft_SDK
-- External Project: Qt5.12.3: 5.12.3
-- External Project: EbsdLib
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/hao_sheng/EMsoft/EMsoftSuperbuild/Debug
Haos-MacBook-Pro:Debug hao_sheng$ make -j
[ 16%] Built target Qt5
[ 22%] Built target hdf5
[ 24%] Performing update step for 'jsonfortran'
[ 47%] Built target Eigen
[ 47%] Performing update step for 'CLFortran'
[ 47%] Built target tbb
[ 48%] Performing build step for 'fftw'
[ 50%] Performing update step for 'bcls'
[ 51%] Performing update step for 'EbsdLib'
CMake Error at /Users/hao_sheng/EMsoft/EMsoft_SDK/superbuild/fftw/Stamp/fftw-build-Debug.cmake:49 (message):
  Command failed: 2

   'make' '-j4'

  See also

    /Users/hao_sheng/EMsoft/EMsoft_SDK/superbuild/fftw/Stamp/fftw-build-*.log

make[2]: *** [/Users/hao_sheng/EMsoft/EMsoft_SDK/superbuild/fftw/Stamp/fftw-build] Error 1
make[1]: *** [CMakeFiles/fftw.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
-- bcls update command succeeded.  See also /Users/hao_sheng/EMsoft/EMsoft_SDK/superbuild/bcls/Stamp/Debug/bcls-update-*.log
-- EbsdLib update command succeeded.  See also /Users/hao_sheng/EMsoft/EMsoft_SDK/superbuild/EbsdLib/Stamp/Debug/EbsdLib-update-*.log
-- CLFortran update command succeeded.  See also /Users/hao_sheng/EMsoft/EMsoft_SDK/superbuild/CLFortran/Stamp/Debug/CLFortran-update-*.log
-- jsonfortran update command succeeded.  See also /Users/hao_sheng/EMsoft/EMsoft_SDK/superbuild/jsonfortran/Stamp/Debug/jsonfortran-update-*.log
[ 55%] Performing configure step for 'CLFortran'
[ 55%] Performing configure step for 'EbsdLib'
[ 55%] Performing configure step for 'bcls'
[ 56%] Performing configure step for 'jsonfortran'
-- CLFortran configure command succeeded.  See also /Users/hao_sheng/EMsoft/EMsoft_SDK/superbuild/CLFortran/Stamp/Debug/CLFortran-configure-*.log
[ 58%] Performing build step for 'CLFortran'
-- jsonfortran configure command succeeded.  See also /Users/hao_sheng/EMsoft/EMsoft_SDK/superbuild/jsonfortran/Stamp/Debug/jsonfortran-configure-*.log
[ 59%] Performing build step for 'jsonfortran'
-- CLFortran build command succeeded.  See also /Users/hao_sheng/EMsoft/EMsoft_SDK/superbuild/CLFortran/Stamp/Debug/CLFortran-build-*.log
[ 60%] Performing install step for 'CLFortran'
-- jsonfortran build command succeeded.  See also /Users/hao_sheng/EMsoft/EMsoft_SDK/superbuild/jsonfortran/Stamp/Debug/jsonfortran-build-*.log
[ 62%] Performing install step for 'jsonfortran'
-- EbsdLib configure command succeeded.  See also /Users/hao_sheng/EMsoft/EMsoft_SDK/superbuild/EbsdLib/Stamp/Debug/EbsdLib-configure-*.log
-- CLFortran install command succeeded.  See also /Users/hao_sheng/EMsoft/EMsoft_SDK/superbuild/CLFortran/Stamp/Debug/CLFortran-install-*.log
[ 63%] Performing build step for 'EbsdLib'
-- jsonfortran install command succeeded.  See also /Users/hao_sheng/EMsoft/EMsoft_SDK/superbuild/jsonfortran/Stamp/Debug/jsonfortran-install-*.log
[ 64%] Completed 'CLFortran'
[ 66%] Completed 'jsonfortran'
[ 70%] Built target CLFortran
[ 74%] Built target jsonfortran
-- EbsdLib build command succeeded.  See also /Users/hao_sheng/EMsoft/EMsoft_SDK/superbuild/EbsdLib/Stamp/Debug/EbsdLib-build-*.log
[ 75%] Performing install step for 'EbsdLib'
-- bcls configure command succeeded.  See also /Users/hao_sheng/EMsoft/EMsoft_SDK/superbuild/bcls/Stamp/Debug/bcls-configure-*.log
[ 77%] Performing build step for 'bcls'
-- bcls build command succeeded.  See also /Users/hao_sheng/EMsoft/EMsoft_SDK/superbuild/bcls/Stamp/Debug/bcls-build-*.log
[ 78%] Performing install step for 'bcls'
-- EbsdLib install command succeeded.  See also /Users/hao_sheng/EMsoft/EMsoft_SDK/superbuild/EbsdLib/Stamp/Debug/EbsdLib-install-*.log
[ 79%] Completed 'EbsdLib'
[ 83%] Built target EbsdLib
-- bcls install command succeeded.  See also /Users/hao_sheng/EMsoft/EMsoft_SDK/superbuild/bcls/Stamp/Debug/bcls-install-*.log
[ 85%] Completed 'bcls'
[ 89%] Built target bcls
make: *** [all] Error 2

The log file is attached here: 

2 files to edit

planner.c:799:12: error: expected ')'
              "(" WISDOM_PREAMBLE " #x%M #x%M #x%M #x%M\n",
                  ^
planner.c:786:25: note: expanded from macro 'WISDOM_PREAMBLE'
#define WISDOM_PREAMBLE PACKAGE "-" VERSION " " STRINGIZE(X(wisdom))
                        ^
planner.c:798:14: note: to match this '('
     p->print(p,
             ^
planner.c:843:10: error: expected ')'
                   "(" WISDOM_PREAMBLE " #x%M #x%M #x%M #x%M\n",
                       ^
planner.c:786:25: note: expanded from macro 'WISDOM_PREAMBLE'
#define WISDOM_PREAMBLE PACKAGE "-" VERSION " " STRINGIZE(X(wisdom))
                        ^
planner.c:842:19: note: to match this '('
     if (!sc->scan(sc,
                  ^
2 errors generated.
make[5]: *** [planner.lo] Error 1
make[4]: *** [all-recursive] Error 1
make[3]: *** [all] Error 2

Could you help take a look into this issue?

**Comment by hsheng94** [comment]
This problem is only encountered when installing on mac. On Linux, there is no such error.

**Comment by imikejackson** [comment]
I think for macOS you would need to use the precompiled binaries of FFTW?
