### ISSUE TITLE
Building hdf5, fftw and Eigen on OSX 10.14

### ISSUE THREAD

**Issue by saransh13** [EMsoft-org/EMsoftSuperbuild#15]
gcc: Apple clang version 11.0.0 (clang-1100.0.33.8)
gfortran: 6.3.0 
Make: 3.14.0
Mac OSX: 10.14 Mojave

Attaching the log files for Eigen and HDF5
[hdf5-build-err.log](https://github.com/EMsoft-org/EMsoftSuperbuild/files/3740830/hdf5-build-err.log)

[Eigen-configure-err.log](https://github.com/EMsoft-org/EMsoftSuperbuild/files/3740834/Eigen-configure-err.log)

[fftw-build-err.log](https://github.com/EMsoft-org/EMsoftSuperbuild/files/3740838/fftw-build-err.log)

**Comment by marcdegraef** [comment]
very strange... I have basically the same configuration and no issues at all; did you do a completely clean build, i.e., delete the old SDK completely?

**Comment by saransh13** [comment]
Yep, did it from scratch. The other packages built successfully, so its
even more confusing.
Is there an option to use build scripts like in the previous version?

**Comment by marcdegraef** [comment]
Can you post the output of the original cmake command?  Sounds to me like you might have a compiler confusion issue...

**Comment by saransh13** [comment]
(py36) bakalau:Debug saransh1$ cmake -DEMsoft_SDK=/Users/saransh1/EMsoft_SDK_5.0.0 -DCMAKE_BUILD_TYPE=Debug ../

CMake Deprecation Warning at CMakeLists.txt:6 (cmake_policy):

  The OLD behavior for policy CMP0042 will be removed from a future version

  of CMake.

 

  The cmake-policies(7) manual explains that the OLD behaviors of all

  policies are deprecated and that a policy should be set to OLD only under

  specific short-term circumstances.  Projects should be ported to the NEW

  behavior and not rely on setting a policy to OLD.

 

 

-- The C compiler identification is AppleClang 11.0.0.11000033

-- The CXX compiler identification is AppleClang 11.0.0.11000033

-- The Fortran compiler identification is GNU 6.3.0

-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc

-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works

-- Detecting C compiler ABI info

-- Detecting C compiler ABI info - done

-- Detecting C compile features

-- Detecting C compile features - done

-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++

-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works

-- Detecting CXX compiler ABI info

-- Detecting CXX compiler ABI info - done

-- Detecting CXX compile features

-- Detecting CXX compile features - done

-- Checking whether Fortran compiler has -isysroot

-- Checking whether Fortran compiler has -isysroot - yes

-- Checking whether Fortran compiler supports OSX deployment target flag

-- Checking whether Fortran compiler supports OSX deployment target flag - yes

-- Check for working Fortran compiler: /usr/local/bin/gfortran

-- Check for working Fortran compiler: /usr/local/bin/gfortran  -- works

-- Detecting Fortran compiler ABI info

-- Detecting Fortran compiler ABI info - done

-- Checking whether /usr/local/bin/gfortran supports Fortran 90

-- Checking whether /usr/local/bin/gfortran supports Fortran 90 -- yes

-- EMsoft_SDK Folder: /Users/saransh1/EMsoft_SDK_5.0.0

-- EMsoft_SDK_FILE:   /Users/saransh1/EMsoft_SDK_5.0.0/EMsoft_SDK.cmake

-- Workspace Folder:   

-- DARWIN_VERSION: 18

-- External Project: fftw

-- External Project: jsonfortran

-- External Project: bcls

-- External Project: CLFortran

-- External Project: Eigen

-- External Project: hdf5

-- External Project: Qt5.9.3

-- Configuring done

-- Generating done

-- Build files have been written to: /Users/saransh1/EMsoftSuperbuild/Debug

**Comment by saransh13** [comment]
Deleting everything and rebuilding from scratch fixed the issue.
