### ISSUE TITLE
error in make

### ISSUE THREAD

**Issue by chauniyal** [EMsoft-org/EMsoftSuperbuild#22]
--- LOG END ---
         error: downloading 'http://dream3d.bluequartz.net/binaries/SDK/Sources/HDF5/hdf5-1.8.20.tar.gz' failed
         status_code: 22
         status_string: "HTTP response code said error"
An error is invoked when while compiling hdf libraries. The reason is that the the URL locations does not exist anymore as they have updated to hdf5....1.10.01.tar.gz now. 
Kindly make this change in the make files to include the new URL.

**Comment by marcdegraef** [comment]
Did you pull the latest version of the SuperBuild and completely rebuild your SDK?  The HDF5 source code is pulled directly from GitHub, not from dream3d.bluequartz.net ... it used to be in the past but this was changed several months ago...
Regards, Marc.

**Comment by chauniyal** [comment]
I did that exactly. Cloned the repository and followed the instructions using CMake. 
During make -j I get the following error.

CMake Error at /home/users/chaunarz/Apps/EMSOFT/SDK/EMsoftSuperbuild/superbuild/hdf5-1.8.20/Stamp/Debug/hdf5-download-Debug.cmake:49 (message):
  Command failed: 1

   '/usr/bin/cmake' '-Dmake=' '-Dconfig=' '-P' '/home/users/chaunarz/Apps/EMSOFT/SDK/EMsoftSuperbuild//superbuild/hdf5-1.8.20/Stamp/Debug/hdf5-download-Debug-impl.cmake'

  See also

    /home/users/chaunarz/Apps/EMSOFT/SDK/EMsoftSuperbuild//superbuild/hdf5-1.8.20/Stamp/Debug/hdf5-download-*.log


CMake Error at /home/users/chaunarz/Apps/EMSOFT/SDK/EMsoftSuperbuild/superbuild/Eigen/Stamp/Debug/Eigen-download-Debug.cmake:49 (message):
  Command failed: 1

   '/usr/bin/cmake' '-Dmake=' '-Dconfig=' '-P' '/home/users/chaunarz/Apps/EMSOFT/SDK/EMsoftSuperbuild//superbuild/Eigen/Stamp/Debug/Eigen-download-Debug-impl.cmake'

  See also

    /home/users/chaunarz/Apps/EMSOFT/SDK/EMsoftSuperbuild//superbuild/Eigen/Stamp/Debug/Eigen-download-*.log


After which I looked up the *err.log file and found the following.
CMake Error at /home/users/chaunarz/Apps/EMSOFT/SDK/EMsoftSuperbuild/superbuild/hdf5-1.8.20/Stamp/Debug/download-hdf5.cmake:159 (message):
  Each download failed!

    error: downloading 'http://dream3d.bluequartz.net/binaries/SDK/Sources/HDF5/hdf5-1.8.20.tar.gz' failed
         status_code: 22
         status_string: "HTTP response code said error"
         log:
         --- LOG BEGIN ---
           Trying 216.196.182.26:80...

  TCP_NODELAY set

  Connected to dream3d.bluequartz.net (216.196.182.26) port 80 (#0)

  GET /binaries/SDK/Sources/HDF5/hdf5-1.8.20.tar.gz HTTP/1.1

  Host: dream3d.bluequartz.net

  User-Agent: curl/7.66.0

  Accept: */*

.............
