### ISSUE TITLE
jsonfortran compile error

### ISSUE THREAD

**Issue by ketancmaheshwari** [EMsoft-org/EMsoftSuperbuild#6]
I see the following compile error from jsonfortran:

~/EMsoft_SDK/superbuild/jsonfortran/Source/jsonfortran/src/json_module.F90:316.52:

        character(kind=CK,len=:),allocatable :: name  !! variable name
                                                    1
Error: Deferred-length character component 'name' at (1) is not yet supported
~/EMsoft_SDK/superbuild/jsonfortran/Source/jsonfortran/src/json_module.F90:316.52:

        character(kind=CK,len=:),allocatable :: name  !! variable name
                                                    1
Error: Deferred-length character component 'name' at (1) is not yet supported
make[5]: *** [CMakeFiles/jsonfortran.dir/src/json_module.F90.o] Error 1
make[4]: *** [CMakeFiles/jsonfortran.dir/all] Error 2
make[3]: *** [all] Error 2

I am passing -DCMAKE_Fortran_COMPILER at the top level to be gfortran 5.x.x but it seems that the variable does not get propagated into the build. Setting PATH and LD_LIBRARY_PATH to the gfortran installation does not help either. However, when I manually build jsonfortran , it does get build. Any suggestions?

**Comment by marcdegraef** [comment]
This is definitely due to the fact that your compiler version is too old; the instructions on the github site specifically state gfortran 6.3 or higher...
Marc

**Comment by ketancmaheshwari** [comment]
The instruction says GFortran 5.2 and above, and I am using gfortran 5.3.0; Additionally, the build of jsonfortran works independently outside of the overall cmake.

**Comment by ketancmaheshwari** [comment]
This worked after I added the -DCMAKE_Fortran_COMPILER=/path/to/gfortran in cmake/External_JsonFortran.cmake file.

**Comment by ghost** [comment]
Yes, on a cluster running module files, this  `projects/JsonFortran.cmake` has to be edited, because despite the command line invoke the correct gcc version, the JsonFortran projects doesn't read it.
Is it possible to fix this ?
